
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: guestbook
  name: pv02
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.99.20
    path: "/pv02"
