apiVersion: v1
kind: Namespace
metadata:
   name: guestbook

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: guestbook
  name: thin-disk
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: thin
