---
apiVersion: v1
kind: Service
metadata:
  name: myhero-ui
  labels:
    app: myhero
    tier: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: myhero
    tier: ui
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-ui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myhero
        tier: ui
    spec:
      containers:
      - name: myhero-ui
        image: hpreston/myhero_ui:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: myhero_app_server
            value: http://myhero-app.demo.vxlan.co
          - name: myhero_app_key
            value: SecureApp
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 48M
      restartPolicy: Always
---
# Inress Rule for N/S Load-Balancing
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myhero-ui-ingress
spec:
  rules:
    - host: myhero-ui.demo.vxlan.co
      http:
        paths:
          - path: /*
            backend:
              serviceName: myhero-ui
              servicePort: 80
